services:
  - type: web
    name: Suinership
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          name: Suinership_db
          type: postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: suinership.onrender.com
    numInstances: 1

