# Generated by Django 5.2.5 on 2025-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_salt',
            field=models.BigIntegerField(default=50944404942521019160377095868802172967, unique=True),
        ),
    ]
