# Generated by Django 5.2.5 on 2025-09-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_salt',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
