# Generated by Django 5.2.5 on 2025-09-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_google_id_user_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_salt',
            field=models.BigIntegerField(default=99291185602356511116087272326556667673, unique=True),
        ),
    ]
