# Generated by Django 5.2.5 on 2025-09-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_salt',
            field=models.BigIntegerField(default=188963769357205458390454656039792763671, unique=True),
        ),
    ]
