# Generated by Django 5.2.5 on 2025-09-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_google_id_remove_user_user_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_salt',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
