# Generated by Django 5.2.5 on 2025-09-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_google_id_user_user_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_salt',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
